language: php

php:
  - 7.1
git:
  submodules: false
install:
    - composer install
script:
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
    - vendor/bin/test-reporter
deploy:
  provider: heroku
  buildpack: php
  api_key: $HEROKU_TOKEN
  app:
    master: marra-nhtsa-staging
    develop: marra-nhtsa-dev
    tags/*: marra-nhtsa
